name: address_search_field
description: An address search field which helps to autocomplete an address by a reference. It can be used to get Directions beetwen two points.
version: 5.0.3
homepage: https://github.com/JosLuna98/address_search_field

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  google_maps_flutter: ^2.1.10
  # flutter_riverpod: ^1.0.4
  dio: ^5.7.0
  flutter_riverpod: ^2.6.1
  # google_maps_flutter: ^2.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: dev.jostech.address_search_field
        pluginClass: AddressSearchFieldPlugin
      ios:
        pluginClass: AddressSearchFieldPlugin
      windows:
        pluginClass: AddressSearchFieldPlugin
      web:
        pluginClass: AddressSearchFieldWeb
        fileName: address_search_field_web.dart